# Generated by Django 5.0.2 on 2024-02-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Kategorie', models.CharField(max_length=100)),
                ('Verkaufspreis', models.IntegerField()),
            ],
        ),
    ]
