# Generated by Django 5.0.2 on 2024-02-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menue', '0003_alter_book_verkaufspreis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Verkaufspreis',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
