# Generated by Django 5.0.2 on 2024-03-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menue', '0005_alter_book_verkaufspreis'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Allergene',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
